import type { ComponentType } from 'react'
import type { IconName, SvgIconProps } from './Icon.types'
import {
    IcBell,
    IcChat,
    IcCheckCircle,
    IcChevronDown,
    IcChevronLeft,
    IcChevronRight,
    IcCloudUpload,
    IcCog,
    IcCollection,
    IcDocumentText,
    IcHome,
    IcLogout,
    IcMusicNote,
    IcPencil,
    IcPhotograph,
    IcPlus,
    IcSparkles,
    IcTemplate,
    IcTrash,
    IcUser,
    IcUsers,
    IcViewGrid,
    IcXCircle,
    IcX
} from './items'

export const iconMap: Record<IconName, ComponentType<SvgIconProps>> = {
    bell: IcBell,
    chat: IcChat,
    'check-circle': IcCheckCircle,
    'chevron-down': IcChevronDown,
    'chevron-left': IcChevronLeft,
    'chevron-right': IcChevronRight,
    'cloud-arrow-up': IcCloudUpload,
    cog: IcCog,
    collection: IcCollection,
    'document-text': IcDocumentText,
    home: IcHome,
    logout: IcLogout,
    'music-note': IcMusicNote,
    pencil: IcPencil,
    photograph: IcPhotograph,
    plus: IcPlus,
    sparkles: IcSparkles,
    template: IcTemplate,
    trash: IcTrash,
    user: IcUser,
    users: IcUsers,
    'view-grid': IcViewGrid,
    'x-circle': IcXCircle,
    'x-mark': IcX,
    x: IcX
}
