// Artist
export const ADD_ARTIST = {
    ATTEMPT: 'ADD_ARTIST_ATTEMPT',
    FAILED: 'ADD_ARTIST_FAILED',
    SUCCEED: 'ADD_ARTIST_SUCCEED'
}

export const GET_ARTIST_BY_ID = {
    ATTEMPT: 'GET_ARTIST_BY_ID_ATTEMPT',
    FAILED: 'GET_ARTIST_BY_ID_FAILED',
    SUCCEED: 'GET_ARTIST_BY_ID_SUCCEED'
}

export const GET_ARTISTS = {
    ATTEMPT: 'GET_ARTISTS_ATTEMPT',
    FAILED: 'GET_ARTISTS_FAILED',
    SUCCEED: 'GET_ARTISTS_SUCCEED'
}

export const UPDATE_ARTIST = {
    ATTEMPT: 'UPDATE_ARTIST_ATTEMPT',
    FAILED: 'UPDATE_ARTIST_FAILED',
    SUCCEED: 'UPDATE_ARTIST_SUCCEED'
}


// Authentication
export const LOGIN = {
    ATTEMPT: 'LOGIN_ATTEMPT',
    FAILED: 'LOGIN_FAILED',
    SUCCEED: 'LOGIN_SUCCEED'
}

export const LOGOUT = {
    ATTEMPT: 'LOGOUT_ATTEMPT',
    FAILED: 'LOGOUT_FAILED',
    SUCCEED: 'LOGOUT_SUCCEED'
}


// Catalog
export const GET_CATALOG_TYPES = {
    ATTEMPT: 'GET_CATALOG_TYPES_ATTEMPT',
    FAILED: 'GET_CATALOG_TYPES_FAILED',
    SUCCEED: 'GET_CATALOG_TYPES_SUCCEED'
}